import Image from 'next/image';
import Link from 'next/link';

import { ClerkProvider, UserButton } from '@clerk/nextjs';

import '../styles/globals.css';
import styles from '../components/layout.module.css';
import utilStyles from '../styles/utils.module.css';

const name = 'Kyle Burns';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <div className={styles.container}>
            <main>{children}</main>
          </div>
        </body>
      </html>
    </ClerkProvider>
  )
}
