import '../styles/globals.css';
import { ClerkProvider, UserButton } from '@clerk/nextjs'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <section>
            <UserButton />
          </section>
          <section>
            {children}
          </section>
        </body>
      </html>
    </ClerkProvider>
  )
}
